version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Primary image where commands will run
    environment:
      FLASK_ENV: test

    steps:
      - checkout  # Check out your project's code

      # Install Backend Dependencies (Flask)
      - run:
          name: Set up Python Environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r backend/requirements.txt

      # Install Frontend Dependencies (React)
      - run:
          name: Install Frontend Dependencies
          command: |
            cd frontend
            npm install

      # Run Backend Tests
      - run:
          name: Run Backend Tests
          command: |
            cd backend
            . ../venv/bin/activate
            pytest

      # Run Frontend Tests
      - run:
          name: Run Frontend Tests
          command: |
            cd frontend
            npm run test

      # Check for linting errors
      - run:
          name: Check Code Linting
          command: |
            cd frontend
            npm run lint
            cd ../backend
            flake8 .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
